<a href="https://colab.research.google.com/github/rajacsp/mlcolab-work/blob/master/Numpy_25.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [0]:
a = np.array(
    [
     [1, 2],
     [3, 4]
    ]
)

In [3]:
a

array([[1, 2],
       [3, 4]])

In [4]:
# Find sum
a.sum()

10

In [5]:
# Find sum with x axis
a.sum(axis = 0)

array([4, 6])

In [6]:
a.sum(axis = 1)

array([3, 7])

In [7]:
a.ndim

2

In [0]:
# Test